### ISSUE TITLE
documentations please

### ISSUE THREAD

**Issue by thecotne** [bholloway/browserify-debug-tools#1]
i think `profile` is what i need but did not figured out how to use it (i am using laravel-elixir)

**Comment by bholloway** [comment]
What is your use case (so I can be sure to cover it)?

**Comment by thecotne** [comment]
my browserify task is very slow and i want to find what makes it so slow

**Comment by bholloway** [comment]
filled out the `readme.md` let me know where that places you now

**Comment by thecotne** [comment]
@bholloway thx
